version: '3'

services:
    book-library:
        build: ./book-library
        volumes:
            - ./book-library:/usr/src/app
        ports:
            - 5001:80
    
    productpage:
        build: ./productpage
        volumes:
            - ./productpage:/usr/src/app
        ports:
            - 5000:80
        depends_on:
            - book-library
    
    detail:
        build: ./detail
        volumes:
            - ./detail:/usr/src/app
        ports:
            - 5002:80
        depends_on:
            - book-library
            
    addbook:
        build: ./addbook
        volumes:
            - ./addbook:/usr/src/app
        ports:
            - 5003:80
        depends_on:
            - book-library
